# Generated by Django 2.1.1 on 2018-10-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('direccion', models.CharField(max_length=256)),
                ('sucursal', models.CharField(choices=[('01', 'Alameda'), ('02', 'Providencia'), ('03', 'Las Condes'), ('04', 'Vitacura')], max_length=2)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('A', 'Abono'), ('R', 'Retiro')], max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.Cliente')),
            ],
        ),
    ]
