# Generated by Django 2.1.1 on 2018-10-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0003_auto_20181001_2124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Cliente',
        ),
    ]
