# Generated by Django 2.1.1 on 2018-10-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0005_userprofileinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='picture',
            new_name='profile_pic',
        ),
    ]
