# Generated by Django 2.1.1 on 2018-10-14 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0009_auto_20181005_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
