# Generated by Django 2.1.1 on 2018-10-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20181004_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='region',
            field=models.IntegerField(null=True),
        ),
    ]
